
services:
    app:
        build:
            context: ./src
            dockerfile: Dockerfile
            args:
                - DISPLAY=${DISPLAY}
                - DEBIAN_FRONTEND=${DEBIAN_FRONTEND}
                - TZ=${TZ}
                - LANG=${LANG}
                - LC_ALL=${LC_ALL}
                - MAVEN_VERSION=${MAVEN_VERSION}
                - JAVA_VERSION=${JAVA_VERSION}
        env_file: ./.env
        environment:
            - DISPLAY=${DISPLAY}
            - DEBIAN_FRONTEND=${DEBIAN_FRONTEND}
            - TZ=${TZ}
            - LANG=${LANG}
            - LC_ALL=${LC_ALL}
            - MYSQL_ADDRESS=${MYSQL_ADDRESS}
            - MYSQL_PORT=${MYSQL_PORT}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3000:3000"
            - "6901:6901"
        stdin_open: true
        tty: true
        networks:
            - app-network
        depends_on:
            - database
        restart: always

    database:
        build:
            context: ./database
            dockerfile: Dockerfile
        env_file: ./.env
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        networks:
            - app-network
        ports:
            - "${MYSQL_PORT}:${MYSQL_PORT}"
        restart: always

networks:
    app-network:
        driver: bridge

volumes:
    mysql-data: {}
