@startuml "diagramme de classe"
skinparam linetype ortho

class Main

package view {

    class MainWindow{
        -title : String
    }

    class MenuWindow{
        -mainPanel : JPanel
        -appMenu : JMenu
        -appItem : JMenuItem

        +openDocumentForm() : void
        +openClientSupplierForm() : void
        +openProductSearchForm() : void
        +openRecipeSearchForm() : void
    }

    'CRUD 1'
    'Read Delete'
    class DocumentTable {
        -documents : ArrayList<Document> // All docs
        -displayDocuments : ArrayList<Document> // Displayed docs in the table
        -typeDocumentFilter : JComboBox
        -startCreationDate : JDatePicker
        -endCreationDate : JDatePicker

        +onFilterClick() : void
        +onCreateClick() : void
        +onUpdateClick(Document) : void
        +onDeleteClick(Document) : void
    }

    ' TODO: Discus if we create one object for both create and update'
    'Create'
    class DocumentCreationForm {
        -id : JTextField
        -commentary : JTextArea
        -checkIsChecked : JCheckBox
        -pickerPlannedSendDate : JDatePicker
        -pickerPlannedReceptionDate : JDatePicker
        -pickerEffectiveSendDate : JDatePicker
        -pickerEffectiveReceptionDate : JDatePicker
        -txtPaymentDelay : JTextField
        -comboWorkflow : JComboBox
        -comboClientSupplier : JComboBox
        -spnStreetNumber : JSpinner
        -spnPostalCode : JSpinner
        -txtStreet : JComboBox
        -txtCity : JComboBox
        -txtCountry : JComboBox

        +onSaveClicked() : void
        +clearForm() : void

        +showError(message : String) : void
        +validateFields() : boolean
    }

    'Update'
    class DocumentUpdateForm {
        -id : JTextField
        -commentary : JTextArea
        -checkIsChecked : JCheckBox
        -pickerPlannedSendDate : JDatePicker
        -pickerPlannedReceptionDate : JDatePicker
        -pickerEffectiveSendDate : JDatePicker
        -pickerEffectiveReceptionDate : JDatePicker
        -txtPaymentDelay : JTextField
        -comboWorkflow : JComboBox
        -comboClientSupplier : JComboBox
        -spnStreetNumber : JSpinner
        -spnPostalCode : JSpinner
        -txtStreet : JComboBox
        -txtCity : JComboBox
        -txtCountry : JComboBox

        +onValidateClick(Document) : void
        +onCancelClick() : void

        +showError(message : String) : void
        +validateFields() : boolean
    }

    'CRUD 2 '
    'Read Delete'
    class ClientSupplierTable {
        -clientSuppliers: ArrayList<ClientSupplier> // All client and supplier
        -displayClientSupplier: ArrayList<ClientSupplier> // Displayed client and supplier in the table
        -isStaff : boolean
        -isClient: boolean
        -isSupplier: boolean
        -typeFilter : JComboBox

        +onFilterClick() : void
        +onCreateClick() : void
        +onUpdateClick(Document) : void
        +onDeleteClick(Document) : void
    }

    'Create'
    class ClientSupplierCreationForm {
        -txtName : JTextField
        -txtFirstName : JTextField
        -txtEmail : JTextField
        -txtVATNumber : JTextField
        -pickerDateBecameClient : JDatePicker
        -boxIsClient : JCheckBox
        -boxIsSupplier : JCheckBox
        -boxIsUs : JCheckBox
        -spnFidelityPoints : JSpinner
        -spnStreetNumber : JSpinner
        -spnPostalCode : JSpinner
        -txtStreet : JComboBox
        -txtCity : JComboBox
        -txtCountry : JComboBox

        +onSaveClicked() : void
        +clearForm() : void

        +showError(message : String) : void
        +validateFields() : boolean
    }

    'Update '
    class ClientSupplierUpdateForm {
        -txtName : JTextField
        -txtFirstName : JTextField
        -txtEmail : JTextField
        -txtVATNumber : JTextField
        -pickerDateBecameClient : JDatePicker
        -boxIsClient : JCheckBox
        -boxIsSupplier : JCheckBox
        -boxIsUs : JCheckBox
        -spnFidelityPoints : JSpinner
        -spnStreetNumber : JSpinner
        -spnPostalCode : JSpinner
        -txtStreet : JComboBox
        -txtCity : JComboBox
        -txtCountry : JComboBox

        +onSaveClicked() : void
        +clearForm() : void

        +showError(message : String) : void
        +validateFields() : boolean
    }

    'Recherche 1 '
    class ProductSearchForm {
        -txtProductName : JTextField
        -comboCategory : JComboBox
        -boxpromotion : JCheckBox
        -btnSearch : JButton
        -table : JTable

        +onSearchClicked() : void
        +onViewClicked() : void
        +clearForm() : void
        +displayResults(List<Product>) : void
    }
    class ProductView {
        -lblName : JLabel
        -lblPriceExclTax : JLabel
        -lblVAT : JLabel
        -lblFidelityPoints : JLabel

        -lblShelf : JLabel
        -lblFloor : JLabel
        -lblQuantity : JLabel
        -lblMinimumThreshold : JLabel
        -lblIsRefrigerated : JLabel

        -lblPromotionPercentage : JLabel
        -lblPromotionActive : JLabel
        -lblRequiredQuantity : JLabel
        -lblPromotionStartDate : JLabel
        -lblPromotionEndDate : JLabel
        -btnBack : JButton

        +displayProduct(Product) : void
    }

    'Recherche 2 '
    class RecipeSearchForm {
        -txtName : JTextField
        -txtProduct : JTextField
        -btnSearch : JButton
        -btnAddProduct : JButton
        -btnViewProduct : JButton
        -table : JTable

        +onAddProductClicked() : void
        +onSearchClicked() : void
        +clearForm() : void
        +displayResults(List<Recipe>) : void
    }
    class RecipeView {
        -tableComposition : JTable
        -txtSteps : JTextArea
        -btnEdit : JButton
        -btnBack : JButton

        +onBackClicked() : void
        +onModifyClicked() : void
        +displayRecipe(Recipe) : void
    }

    'Recherche 3 '
    class ClientSupplierSearchForm {
        -txtName : JTextField
        -txtEmail : JTextField
        -boxFidelityValid : JCheckBox
        -table : JTable

        +onLoadClicked() : void
        +onSearchClicked() : void
        +clearForm() : void
        +displayResults(List<ClientSupplier>) : void
    }

    'Tâche métier 1'
    class StockAlertView {
        -suppliers : ArrayList<ClientSupplier>
        -selectedSupplier :ClientSupplier
        -products : ArrayList<ProductRow>
        -selectedProducts : ArrayList<ProductRowViewModel>
        -productTable : JTable

        +onSupplierSelected(supplier :ClientSupplier) : void
        +onCreatePurchaseOrderClicked() : void
    }
    class OrderCreationView {
        -selectedSupplier :ClientSupplier
        -productsTable : JTable
        -createButton : JButton
        -cancelButton : JButton

        +displayProducts(products : ArrayList<Product>) : void
        +onQuantityChanged(productId : int, quantity : int) : void

        +onCreateOrderClicked() : void
        +onCancelClicked() : void
    }

    'Tâche métier 2'
    class TicketView {
        - txtSearchProduct : JTextField
        - btnScan : JButton
        - productTable : JTable
        - ticketTable : JTable
        - btnAddItem : JButton
        - btnRemoveItem : JButton
        - btnNext : JButton

        + displayProducts(products : ArrayList<Product>) : void
        + displayCart(items : ArrayList<TicketItem>) : void
        + updateTotal(total : double) : void

        + onAddItem(product : Product) : void
        + onRemoveItem(item : TicketItem) : void
        + onNextClicked() : void
    }
    class TicketClientSelectView {
        - clients : ArrayList<ClientSupplier>
        - selectedClient : ClientSupplier
        - comboSearchClient : JComboBox
        - btnNewClient : JButton
        - btnScanCard : JButton
        - btnBack : JButton
        - btnNext : JButton

        + displaySelectedClient(ClientSupplier)

        + onNewClientClicked()
        + onScanCardClicked()
        + onBackClicked()
        + onNextClicked()
    }
    class TicketPaymentView {
        - client : ClientSupplier
        - btnUsePoints : JButton
        - comboPaymentMethod : JComboBox

        - btnBack : JButton
        - btnPay : JButton

        + displayClient(ClientSupplier) : void
        + displayLoyalty(int available, int used)
        + displaySummary(double subtotal, double discount, double total) : void
        + showPaymentStatus() : void

        + onUsePointsClicked() : void
        + onPaymentMethodChanged() : void
        + onBackClicked() : void
        + onPayClicked() : void
    }

    Main --> MainWindow
    MainWindow --> MenuWindow

    MenuWindow --> ClientSupplierTable
    MenuWindow --> DocumentTable
    MenuWindow --> RecipeSearchForm
    MenuWindow --> ProductSearchForm
    MenuWindow --> ClientSupplierSearchForm
    MenuWindow --> TicketView
    MenuWindow --> RecipeView
    MenuWindow --> StockAlertView

    DocumentTable --> DocumentUpdateForm
    DocumentTable --> DocumentCreationForm

    ClientSupplierTable --> ClientSupplierCreationForm
    ClientSupplierTable --> ClientSupplierUpdateForm

    StockAlertView --> OrderCreationView

    TicketView --> TicketClientSelectView
    TicketView --> ProductView
    TicketClientSelectView --> TicketPaymentView
}

package controller {

    class DocumentController {
        +getAllDocuments() : List<Document>
        +createDocument(title : String, commentary : String) : void
        +updateDocument(id : int, title : String, commentary : String) : void
        +deleteDocument(id : int) : void
    }

    class ClientSupplierController {
        +getAllClientsSuppliers() : List<ClientSupplier>
        +createClientSupplier(name : String, email : String) : void
        +updateClientSupplier(id : int, name : String, email : String) : void
        +deleteClientSupplier(id : int) : void
    }

    class ProductSearchController {
        +searchProducts(name : String, category : String, promotion : boolean) : List<Product>
    }

    class RecipeSearchController {
        +searchRecipes(name : String, product : String) : List<Recipe>
    }

    class ClientSupplierSearchController {
        +search(name : String, email : String, fidelityValid : boolean) : List<ClientSupplier>
    }

    ' TODO: Which attributes should be included ? Which methods should be  created ?'
    class StockManagementController {

    }
}

' VIEW → CONTROLLER
DocumentCreationForm --> DocumentController
DocumentTable --> DocumentController
DocumentUpdateForm --> DocumentController
ClientSupplierTable --> ClientSupplierController
ClientSupplierCreationForm --> ClientSupplierController
ClientSupplierUpdateForm --> ClientSupplierController
ProductSearchForm --> ProductSearchController
RecipeSearchForm --> RecipeSearchController
ClientSupplierSearchForm --> ClientSupplierSearchController
Main ..> StockManagementController: << Thread >>

package business {

    class DocumentManager {
        +getDocuments() : List<Document>
        +getDocument(id : int) : Document
        +getDocumentTypes() : List<TypeDocument>
        +createDocument(commentary : String) : void
        +updateDocument(id : int, commentary : String) : void
        +deleteDocument(id : int) : void

        note "TODO: Update to take into account the different type of documents and there attributes"
    }

    class ClientSupplierManager {
        +getAllClientsSuppliers() : List<ClientSupplier>
        +getClientSupplier(id: int) : ClientSupplier
        +createClientSupplier(name : String, email : String) : void
        +updateClientSupplier(id : int, name : String, email : String) : void
        +deleteClientSupplier(id : int) : void
    }

    class ProductManager {
        +searchProducts(name : String, category : String, promotion : boolean) : List<Product>
        +getAllProduct() : List<Product>
        +getProductSupplier(Product) : List<Product>
    }

    class RecipeSearchManager {
        +searchRecipes(name : String, product : String) : List<Recipe>
    }
}

' CONTROLLER → BUSINESS
DocumentController --> DocumentManager
ClientSupplierController --> ClientSupplierManager
ProductSearchController --> ProductManager
RecipeSearchController --> RecipeSearchManager
ClientSupplierSearchController --> ClientSupplierManager
StockManagementController --> ProductManager

package data {

    class SingletonConnection {
        -connexionUnique : Connection
        +getInstance() : Connection
    }

    class ClientSupplierDBAccess {
        +getAll() : List<ClientSupplier>
        +getById(id : int) : ClientSupplier
        +insert(c : ClientSupplier) : void
        +update(c : ClientSupplier) : void
        +delete(id : int) : void
    }

    class EmployeeDBAccess {
        +getAll() : List<Employee>
        +getByMatricule(matricule : int) : Employee
        +insert(e : Employee) : void
        +update(e : Employee) : void
        +delete(matricule : int) : void
    }

    class DocumentDBAccess {
        +getAll() : List<Document>
        +getById(id : int) : Document
        +insert(d : Document) : void
        +update(d : Document) : void
        +delete(id : int) : void
    }

    class ProductDBAccess {
        +getAll() : List<Product>
        +getById(id : int) : Product
        +insert(p : Product) : void
        +update(p : Product) : void
        +delete(id : int) : void
    }

    class RecipeDBAccess {
        +getAll() : List<Recipe>
        +getById(id : int) : Recipe
        +insert(r : Recipe) : void
        +update(r : Recipe) : void
        +delete(id : int) : void
    }

    ClientSupplierDBAccess --> SingletonConnection
    EmployeeDBAccess --> SingletonConnection
    DocumentDBAccess --> SingletonConnection
    ProductDBAccess --> SingletonConnection
    RecipeDBAccess --> SingletonConnection

}

' BUSINESS → DATA
DocumentManager --> DocumentDBAccess
ClientSupplierManager --> ClientSupplierDBAccess
ProductManager --> ProductDBAccess
RecipeSearchManager --> RecipeDBAccess

package exception {
    exception InvalidUserException

    exception InvalidClientSupplierException
    exception InvalidDocumentException
    exception InvalidProductException
    exception InvalidRecipeException
    exception NotFoundException

    exception DataValidationException
    exception DatabaseConnectionException
}

' EXCEPTIONS
DocumentController ..> InvalidDocumentException
ClientSupplierController ..> InvalidClientSupplierException
ProductSearchController ..> InvalidProductException
RecipeSearchController ..> InvalidRecipeException

DocumentManager ..> DataValidationException
ClientSupplierManager ..> DataValidationException
ProductManager ..> DataValidationException
RecipeSearchManager ..> DataValidationException

DocumentDBAccess ..> DatabaseConnectionException
ClientSupplierDBAccess ..> DatabaseConnectionException
ProductDBAccess ..> DatabaseConnectionException
RecipeDBAccess ..> DatabaseConnectionException

package model {
    class Locality {
        -postalCode : int
        -city : String
    }

    class Address {
        -streetName : String
        -streetNumber : int
    }

    Address --> Locality

    class Employee {
        -matricule : String
        -lastname : String
        -firstname : String
        -phoneNumber : String
        -email : String
        -IBAN : String
        -salaryPerHour : float
        -nbHourPerWeek : int
        -entryDate : Date
        -nbPaidHoliday : int
        -password : String
    }

    Employee --> Address
    Employee "0..*" --> "0..1" Employee : manager

    class Pointage {
        -date : Date
        -startTime : Time
        -endTime : Time
    }

    Pointage "*" --> "1" Employee

    class Function {
        -name : String
    }

    class Position {
    }

    Position "*" --> "*" Employee
    Position "*" --> "1" Function

    class AbsenceType {
        -name : String
    }

    class Absence {
        -startDate : Date
        -endDate : Date
        -description : String
    }

    Absence "*" --> "1" AbsenceType
    Absence "*" --> "1" Employee

    class ClientSupplier {
        -id : int
        -name : String
        -firstName : String
        -email : String
        -phoneNumber : String
        -isClient : bool
        -isSupplier : bool
        -VATNumber : String
        -dateBecameClient : Date
    }

    ClientSupplier "*" --> "1" Address

    class FidelityCard {
        -id : int
        -totalPoint : int
        -isValid : bool
    }

    FidelityCard "1" --> "1" ClientSupplier

    class WorkflowType {
        -name : String
        -isBuy : bool
        -isSupplier : bool
        -isInternal : bool
    }

    class Status {
        -name : String
    }

    class Workflow {
        -id : String
    }

    Workflow "*" --> "1" Status
    Workflow "*" --> "1" WorkflowType

    class DocumentType {
        -name: String
    }

    class Document {
        -id : int
        -date : Date
        -plannedSendDate : Date
        -plannedReceptionDate : Date
        -effectiveSendDate : Date
        -effectiveReceptionDate : Date
        -paymentDelay : int
        -commentary : String
        -isChecked : bool
    }

    Document "*" --> "1" Workflow
    Document "*" --> "1" ClientSupplier
    Document "*" --> "1" Address
    Document "*" --> "1" DocumentType

    class ProductCategory {
        -name : String
    }

    class Product {
        -id : int
        -name : String
        -price : float
        -VAT : int
        -fidelityPoint : int
    }

    Product "*" --> "1" ProductCategory

    class Promotion {
        -requiredQuantity : int
        -discount : int
        -startDate : Date
        -endDate : Date
        -name : String
    }

    Promotion "*" --> "*" Product

    class Location {
        -shelf : String
        -floor : String
    }

    class Quantity {
        -nbProduct : int
    }

    Quantity "*" --> "1" Product
    Quantity "*" --> "1" Location

    class Recipe {
        -name : String
        -explanation : String
    }

    class Composition {
        -quantity : int
    }

    Composition "*" --> "1" Recipe
    Composition "*" --> "1" Product

    class Detail {
        -id : int
        -quantity : float
        -price : float
    }

    Detail "*" --> "1" Document
    Detail "*" --> "1" Product

    class Batch {
        -id : int
        -expirationDate : Date
        -originCountry : String
    }

    Batch "*" --> "1" Product
    Batch "*" --> "1" Detail

    'ModelView'
    class ProductRowViewModel {
        - productName : String
        - currentStock : int
        - minimumThreshold : int
        - quantityToOrder : int
        - status : String
        - isSelected : boolean
    }
    class TicketItem {
        - product : Product
        - quantity : int
        - price : double
    }
}

' MODEL
' DocumentController ..> Document
' ClientSupplierController ..> ClientSupplier
' ProductSearchController ..> Product
' RecipeSearchController ..> Recipe

' DocumentManager ..> Document
' ClientSupplierManager ..> ClientSupplier
' ProductManager ..> Product
' RecipeSearchManager ..> Recipe

' DocumentDBAccess ..> Document
' ClientSupplierDBAccess ..> ClientSupplier
' ProductDBAccess ..> Product
' RecipeDBAccess ..> Recipe

view ..> model
controller ..> model
business ..> model
data ..> model


@enduml