@startuml "exception class diagram"

title "Diagramme de class du package Exception"

' top to bottom direction
skinparam linetype ortho
' skinparam linetype polyline

package exception {
    exception InvalidUserException

    exception InvalidClientSupplierException
    exception InvalidDocumentException
    exception InvalidProductException
    exception InvalidRecipeException
    exception NotFoundException

    exception DataValidationException
    exception DatabaseConnectionException
}


@enduml 